# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CampusIn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod "BSImagePicker", "~> 3.1"
pod 'lottie-ios'
pod 'SideMenu'
pod 'MessageKit'
pod 'SnapKit', '~> 5.6.0'
  # Pods for CampusIn

end
