# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CampusIn' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FSCalendar'
pod 'Alamofire'
pod "BSImagePicker", "~> 3.1"
pod 'lottie-ios'
pod 'SideMenu'
pod 'MessageKit'
pod 'SnapKit', '~> 5.6.0'
  # Pods for CampusIn

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
